run:
  tests: false
  modules-download-mode: vendor

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 80
    statements: 60
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(kube8-operator) # Captures all imports that start with the given prefix.
  gocritic:
    disabled-checks:
      - sloppyLen
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: kube8-operator
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  varnamelen:
    ignore-names:
      - ok
      - err

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gci
    - gocritic
    - goconst
    - goimports
    - gofmt
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - prealloc
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - tagalign
    - tagliatelle
    - usestdlibvars
    - rowserrcheck
    - sqlclosecheck
    - godot
    - godox
    - asasalint
    - cyclop
    - gochecknoglobals
    - interfacebloat
    - nilnil
    - noctx
    - goprintffuncname
    - nonamedreturns
    - contextcheck
    - bodyclose
    - bidichk
    - staticcheck
    - durationcheck
    - errname
    - mirror
    - ireturn
    - nosprintfhostport
    - predeclared
    - promlinter
    - errorlint
    - gocheckcompilerdirectives
  fast: false
