project_name: kube8-operator
env:
  - CGO_ENABLED=0
builds:
  - id: "{{.ProjectName}}"
    main: ./cmd/{{.ProjectName}}/main.go
    ldflags:
      - -s -w
    ignore:
      - goarch: '386'
dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    ids:
      - "{{.ProjectName}}"
    image_templates:
      - "{{.Env.REGISTRY}}/{{.ProjectName}}:latest"
      - "{{.Env.REGISTRY}}/{{.ProjectName}}:v{{.Version}}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--force-rm"
      - "--label={{.Env.LABEL_DOMAIN}}/build={{.Version}}"
      - "--label={{.Env.LABEL_DOMAIN}}/commit={{.FullCommit}}"
      - "--label={{.Env.LABEL_DOMAIN}}/date={{.Date}}"
      - "--label={{.Env.LABEL_DOMAIN}}/version={{.Env.GOVERSION}}"
      - "--label={{.Env.LABEL_DOMAIN}}/name={{.ProjectName}}"
signs:
  - artifacts: all
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^values:"
      - typo
release:
  github:
    owner: rmschick
    name: kube8-operator
  prerelease: auto
