---
# Source: cisco-amp-collector/templates/common.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: cisco-amp-collector-main
  labels: 
    helm.sh/chart: cisco-amp-collector-0.0.1
    app.kubernetes.io/name: cisco-amp-collector
    app.kubernetes.io/instance: cisco-amp-collector-main
    cy_dept: platform-engineering
    cy_dept_group: data
    cy_env_type: development
    cy_env_name: gke-dev
    cy_tenant_ref: CYENGDEV
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  configuration.yaml: "Y2lzY29BTVA6CiAgYXBpS2V5OiAxNzNkMjQ4My0zM2YyLTQxOTQtOWM5OS02Yzg3YzAxY2U3NTEKICBjbGllbnRJRDogM2ZiMTAyYzU1NDA1YWQ4Y2VhMjgKY3Vyc29yOgogIHByb2plY3RJRDogY3lkZXJlcy1kZXYKbWV0YWRhdGE6CiAgY3VzdG9tZXI6CiAgICBpZDogYzZkMjJlMDQtNTAxMC00NTAwLWEyZWEtMDJjNDgwYWUyNzk0CiAgICBuYW1lOiBjeWRlcmVzCiAgZW52aXJvbm1lbnQ6IGRldmVsb3BtZW50CiAgbGFiZWxzOgogICAgdGVzdDogdGVzdGluZy11cGRhdGUKICB0ZW5hbnQ6CiAgICBhbGlhczogIiIKICAgIGlkOiBlYjg0NDU0NS00MjZhLTRmYzItODM2YS0yZDk5ZDI2MjZjNzIKICAgIHJlZmVyZW5jZTogQ1lFTkdERVYKc2VydmVyOgogIGVudHJ5cG9pbnRzOgogICAgaW50cm9zcGVjdGlvbjoKICAgICAgYWNjZXNzbG9nOgogICAgICAgIHJlcXVlc3RzOgogICAgICAgICAgaGVhZGVyczoKICAgICAgICAgICAgZGVmYXVsdDogZHJvcAogICAgICAgICAgICBvdmVycmlkZToge30KICAgICAgICAgIGluY2x1ZGVCb2R5OiBmYWxzZQogICAgICAgICAgd3JpdGU6IGZhbHNlCiAgICAgICAgcmVzcG9uc2VzOgogICAgICAgICAgaGVhZGVyczoKICAgICAgICAgICAgZGVmYXVsdDogZHJvcAogICAgICAgICAgICBvdmVycmlkZToge30KICAgICAgICAgIGluY2x1ZGVCb2R5OiBmYWxzZQogICAgICAgICAgd3JpdGU6IGZhbHNlCiAgICAgIGVuZHBvaW50czoKICAgICAgLSBkZWJ1ZwogICAgICAtIG1ldGEKICAgICAgLSBtZXRyaWNzCiAgICAgIGhvc3Q6IDAuMC4wLjAKICAgICAgaWRsZVRpbWVvdXQ6IDNzCiAgICAgIG1ldHJpY3M6CiAgICAgICAgZW5hYmxlZDogZmFsc2UKICAgICAgbWlkZGxld2FyZTogW10KICAgICAgcG9ydDogODg4OAogICAgICByZWFkVGltZW91dDogM3MKICAgICAgd3JpdGVUaW1lb3V0OiAzcwogIGxpZmVjeWNsZToKICAgIGRyYWluVGltZW91dDogNXMKICAgIGdyYWNlZnVsVGltZW91dDogNXMKICAgIHNodXRkb3duVGltZW91dDogNXM="
---
# Source: cisco-amp-collector/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: cisco-amp-collector-main-private
  labels: 
    helm.sh/chart: cisco-amp-collector-0.0.1
    app.kubernetes.io/name: cisco-amp-collector
    app.kubernetes.io/instance: cisco-amp-collector-main
    cy_dept: platform-engineering
    cy_dept_group: data
    cy_env_type: development
    cy_env_name: gke-dev
    cy_tenant_ref: CYENGDEV
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    privateService: "true"
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: introspection
    protocol: TCP
    name: introspection
  selector: 
    app.kubernetes.io/name: cisco-amp-collector
    app.kubernetes.io/instance: cisco-amp-collector-main
---
# Source: cisco-amp-collector/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-amp-collector-main
  labels: 
    helm.sh/chart: cisco-amp-collector-0.0.1
    app.kubernetes.io/name: cisco-amp-collector
    app.kubernetes.io/instance: cisco-amp-collector-main
    cy_dept: platform-engineering
    cy_dept_group: data
    cy_env_type: development
    cy_env_name: gke-dev
    cy_tenant_ref: CYENGDEV
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: cisco-amp-collector
      app.kubernetes.io/instance: cisco-amp-collector-main
  strategy: 
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 40aba06c1f3b21c0c4a2225ea5b67c890704f636ac1302da53bd6128658e2283
      labels: 
        helm.sh/chart: cisco-amp-collector-0.0.1
        app.kubernetes.io/name: cisco-amp-collector
        app.kubernetes.io/instance: cisco-amp-collector-main
        cy_dept: platform-engineering
        cy_dept_group: data
        cy_env_type: development
        cy_env_name: gke-dev
        cy_tenant_ref: CYENGDEV
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: collector
        image: "us-central1-docker.pkg.dev/cyderes-dev/cyderes-container-repo/cisco-amp-collector:latest"
        imagePullPolicy: 
        resources: 
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 25m
            memory: 128Mi
        livenessProbe: 
          httpGet:
            path: /meta/liveness
            port: introspection
            scheme: HTTP
            httpHeaders:
            - name: x-k8s-probe
              value: liveness
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe: 
          httpGet:
            path: /meta/readiness
            port: introspection
            scheme: HTTP
            httpHeaders:
            - name: x-k8s-probe
              value: readiness
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 8888
          protocol: TCP
          name: introspection
        env:
        - name: METADATA.INSTANCE
          value: cisco-amp-collector-main
        - name: METADATA.INFRASTRUCTURE.NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METADATA.INFRASTRUCTURE.POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METADATA.INFRASTRUCTURE.NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METADATA.INFRASTRUCTURE.CLUSTER
          value: gke-dev
        - name: METADATA.INFRASTRUCTURE.TYPE
          value: KUBERNETES
        volumeMounts:
        - mountPath: /etc/collector
          name: collector-configuration
          readOnly: true
        - mountPath: /etc/integration
          name: collector-configuration
          readOnly: true
      terminationGracePeriodSeconds: 

      volumes:
      - name: collector-configuration
        secret:
          secretName: cisco-amp-collector-main
---
# Source: cisco-amp-collector/templates/common.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cisco-amp-collector-main
  labels:
    helm.sh/chart: cisco-amp-collector-0.0.1
    app.kubernetes.io/name: cisco-amp-collector
    app.kubernetes.io/instance: cisco-amp-collector-main
    cy_dept: platform-engineering
    cy_dept_group: data
    cy_env_type: development
    cy_env_name: gke-dev
    cy_tenant_ref: CYENGDEV
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    release: "prometheus-data"
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 10s
    path: /metrics/prometheus
    port: introspection
  namespaceSelector:
    matchNames:
    - poc-testing
  selector:
    matchLabels: 
      app.kubernetes.io/name: cisco-amp-collector
      app.kubernetes.io/instance: cisco-amp-collector-main
      privateService: "true"
