apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: collectors.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                collector:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Name of the collector
                    version:
                      type: string
                      description: Version of the collector
                    configuration:
                      type: string
                      description: Customer's Configuration of the collector
                tenant:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Tenant ID of the customer being deployed
                    reference:
                      type: string
                      description: Ref of the tenant
                    instance:
                      type: string
                      description: Instance of the tenant this collector is deployed for
                environment:
                  type: string
                  description: Environment
          required:
            - metadata
            - spec
  scope: Namespaced
  names:
    plural: collectors
    singular: collector
    kind: Collector
    shortNames:
      - collector
