apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: collectors.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: collectors
    singular: collector
    kind: Collector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # collector: {name, version, configuration}
                collector:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Name of the collector
                    version:
                      type: string
                      description: Version of the collector
                    configuration:
                      type: string
                      description: Customer's Configuration of the collector
                # tenant: {id, reference, instance}
                tenant:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Tenant ID of the customer being deployed
                    reference:
                      type: string
                      description: Ref of the tenant
                    instance:
                      type: string
                      description: Instance of the tenant this collector is deployed for
                # cluster will define the environment (dev, prod, etc)
                cluster:
                  type: string
                  description: cluster
          required:
            - metadata
            - spec
      # subresources for the custom resource
      subresources:
      # enables the status subresource
        status: {}
