# resource
apiVersion: example.com/v1
kind: Collector
metadata:
  name: cyengdev-duo-collector
  namespace: poc-testing
  labels:
    helm.sh/chart: duo-collector-0.0.1
    app.kubernetes.io/name: duo-collector
    app.kubernetes.io/instance: cyengdev
    cy_dept: platform-engineering
    cy_dept_group: data
    cy_env_type: development
    cy_env_name: gke-dev
    cy_tenant_ref: CYENGDEV
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  collector:
    name: duo-collector
    version: latest
    configuration: ZW52aXJvbm1lbnQ6ICJkZXZlbG9wbWVudCIKY2x1c3RlcjogImdrZS1kZXYiCgpjbXM6CiAgbWV0YWRhdGE6CiAgICBjdXN0b21lcjoKICAgICAgaWQ6IGM2ZDIyZTA0LTUwMTAtNDUwMC1hMmVhLTAyYzQ4MGFlMjc5NAogICAgICBuYW1lOiBjeWRlcmVzCiAgICB0ZW5hbnQ6CiAgICAgIGlkOiBlYjg0NDU0NS00MjZhLTRmYzItODM2YS0yZDk5ZDI2MjZjNzIKICAgICAgcmVmZXJlbmNlOiBDWUVOR0RFVgoKY29uZmlndXJhdGlvbjoKICBkdW86CiAgICBpbnRlZ3JhdGlvbktleTogRElUN0xUSzZKMVVJMERTOFpOV0sKICAgIGhvc3Q6IGFwaS0xZTNiNmYyNC5kdW9zZWN1cml0eS5jb20KICAgIHNlY3JldEtleTogYkVlUW5OTmpEODNkRjZCdHlnQkRUbmJOMW5HMXZBU2lMNDl0dkQ1Zg==
  tenant:
    id: "eb844545-426a-4fc2-836a-2d99d2626c72"
    reference: poc-testing
    instance: main
  cluster: gke-dev
