name: "PR Checks"

on:
  pull_request:
    branches:
      - main

env:
  CGO_ENABLED: "0"

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1alpha.51.2
          args: --timeout=5m
      - name: Run Tests
        run: go install gotest.tools/gotestsum@latest && make test
