name: "Release CI"

on:
  push:
    tags:
      - 'v*'

env:
  CGO_ENABLED: "0"
  GOLANGCI_VERSION: "v1.64.5"

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
