name: "Snapshot CI"

on:
  push:
    branches:
      - main

env:
  CGO_ENABLED: "0"
  GOLANGCI_VERSION: "v1.64.5"

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          args: --timeout=5m
      - name: Run Tests
        run: go install gotest.tools/gotestsum@latest && make test
